@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "fil.l3.coo.competitions.Competition",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_3399 { 
   	label=l3
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1154450340 { 
   	label=coo
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Competition737017217[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Competition</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   competitors: List&lt;Competitor&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ displayRanking(rank: Map&lt;Competitor, Integer&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ displayWinner()</TD></TR>
<TR><TD ALIGN="LEFT" >+ isPowerOfTwo(x: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ play()</TD></TR>
<TR><TD ALIGN="LEFT" >+ play(c: List&lt;Competitor&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ playMatch(c1: Competitor, c2: Competitor): Competitor</TD></TR>
<TR><TD ALIGN="LEFT" >+ ranking(): Map&lt;Competitor, Integer&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Competitor855064602[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Competitor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nbPoints: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addOnePoint()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

League737017217[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)League</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ displayWinner()</TD></TR>
<TR><TD ALIGN="LEFT" >+ play()</TD></TR>
<TR><TD ALIGN="LEFT" >+ play(c: List&lt;Competitor&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ playMatch(c1: Competitor, c2: Competitor): Competitor</TD></TR>
<TR><TD ALIGN="LEFT" >+ winnerOfTheLeague(): Competitor</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MapUtil250765189[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MapUtil</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ sortByDescendingValue(map: Map&lt;K, V&gt;): Map&lt;K, V&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Tournament737017217[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Tournament</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ displayWinner()</TD></TR>
<TR><TD ALIGN="LEFT" >+ play(c: List&lt;Competitor&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ play()</TD></TR>
<TR><TD ALIGN="LEFT" >+ playMatch(c1: Competitor, c2: Competitor): Competitor</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Competition737017217 -> Competitor855064602[label="competitors
[0..*]"];
Competition737017217 -> League737017217[arrowhead=none, arrowtail=empty, dir=both];
Competition737017217 -> MapUtil250765189[label="ranking() -> sortByDescendingValue()"];
Competition737017217 -> Tournament737017217[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml